logging:
  level:
    org.springframework.web: ERROR
    com.example.springboot: ${app_loglevel:INFO}
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %10.10t [%40.-40logger{39}] %X{txnId} ${LOG_LEVEL_PATTERN:%5.-5p} - %m%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %5level %logger{15} - %msg%n"
file: ./logs/application.log

spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  config:
    import:
      - file:src/main/resources/application.yml
      - classpath:/application.yml

secrets:
  db:
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:letmein1234}

springdoc.show-actuator: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
# allows us to programmatically and dynamically set logging levels to specific values
# curl -s http://localhost:8080/actuator/loggers
# curl -i -X POST -H 'Content-Type: application/json' -d '{"configuredLevel": "TRACE"}' http://localhost:8080/actuator/loggers/com.example.springboot.controller.HelloController
    loggers:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
